Vagrant.configure(2) do |config|
    # Part 2: K3s and three simple applications
    config.vm.define "oelazzouS" do |control|
      control.vm.box = "ubuntu/bionic64"  # Ubuntu bionic64
      control.vm.network "private_network", type: "static", ip: "192.168.42.110"  # static ip add
      control.vm.hostname = "oelazzouS"
      control.vm.provision "file", source: "configuration/app1", destination: "/tmp/app1"
      control.vm.provision "file", source: "configuration/app2", destination: "/tmp/app2"
      control.vm.provision "file", source: "configuration/app3", destination: "/tmp/app3"
      control.vm.provision "file", source: "configuration/deploy.yaml", destination: "/tmp/deploy.yaml"
      control.vm.provider "virtualbox" do |v|
        v.memory = 1024  # Adjust memory as needed (512 MB or 1024 MB)
        v.cpus = 2
      end
      control.vm.provision "shell", privileged: true, path: "script.sh"  # installing k3s in Server machine
    end
  end
  